### PR TITLE
Filter out duplicate trusted task records

### PR DESCRIPTION
**Pull request by zregvart**
This filters out all duplicate trusted task records based on their reference. Previously we would de-duplicate only if the records were adjacent.

Reference: https://issues.redhat.com/browse/EC-1015

### CODE REVIEW

**Comment by lcarva** [comment]
> Previously we would de-duplicate only if the records were adjacent.

This was very much intentional: https://issues.redhat.com/browse/HACBS-2394

**Comment by zregvart** [comment]
It seems that the schema check in ec-policies needs to change to allow duplicate entries then. 

I'm not sure that build-definitions can produce equal digests for two builds, the git references should be different and the images should have different digests as they differ in annotations and in the config/created.

**Comment by lcarva** [comment]
> It seems that the schema check in ec-policies needs to change to allow duplicate entries then.
:+1: 

> I'm not sure that build-definitions can produce equal digests for two builds, the git references should be different and the images should have different digests as they differ in annotations and in the config/created.

I don't remember exactly the scenario in which this may occur, but it may have something to do with the build scripts taking shortcuts to not rebuild an image bundle.

**Comment by zregvart** [comment]
> I don't remember exactly the scenario in which this may occur, but it may have something to do with the build scripts taking shortcuts to not rebuild an image bundle.

Let's not find out, shall we...

**Pull request closed without merging**
