### PR TITLE
Keep versioned GitHub releases

### PR DESCRIPTION
**Pull request by simonbaird**
The idea is to make it easier for someone to use a known version of EC for the sake of stability.

Ref: [EC-602](https://issues.redhat.com/browse/EC-602)

### CODE REVIEW

**Review by lcarva — APPROVED** [review]

**Comment by simonbaird** [comment]
I'll probably merge once it goes green.

**Comment by simonbaird** [comment]
Looks like the acceptance failure is a timeout (maybe) related to `docker.io/wiremock`, and the EC failure is due to a known issue, [maybe fixed by ](https://github.com/redhat-appstudio/build-definitions/pull/969).

**Comment by simonbaird** [comment]
Hold up, I found this: `  suite.go:532: updating local metadata and targets: error updating to TUF remote mirror: tuf: failed to decode root.json: expired at 2024-04-30 19:59:40 +0000 UTC`

So maybe we have a expiration date to bump.

**Comment by simonbaird** [comment]
Rebased on the tuf root/signed image refresh in #1576 which should get the tests passing.

**Comment by simonbaird** [comment]
Konflux EC check failure is a known issue. Everything else is green. Let's merge.

**Pull request merged**
