### PR TITLE
Fix duplicated entries in successes

### PR DESCRIPTION
**Pull request by lcarva**
https://issues.redhat.com/browse/HACBS-2268

### CODE REVIEW

**Comment by lcarva** [comment]
I'm getting 20 successes with this patch. If I use ec-cli from before the issue was introduced, I get 18. The two additional ones are `cve.cve_results_found` and `provenance_materials.git_clone_source_matches_provenance`.

I'm digging into what is actually expected here. Was there a bug that got fixed to explain this?

**Review by mbestavros — APPROVED** [review]
LGTM!

**Review by joejstuart — APPROVED** [review]

**Comment by lcarva** [comment]
Merging this. the failed RHTAP CI seems unrelated. Trying to address it here: https://github.com/enterprise-contract/ec-cli/pull/731

**Review by zregvart — COMMENTED** [review]
Awesome!

**Pull request merged**
