### PR TITLE
Big format update from lsp/gopls via LazyVim

### PR DESCRIPTION
**Pull request by simonbaird**
It all seems pretty reasonable. Let's consider.

### CODE REVIEW

**Review by zregvart — APPROVED** [review]
I like your editor friend

**Comment by lcarva** [comment]
Does `go fmt` agree?

**Comment by simonbaird** [comment]
Not sure how to enforce this, maybe we can figure it out and make a CI format checker.

**Comment by simonbaird** [comment]
Revision is just a new commit message.

**Comment by simonbaird** [comment]
Oh I cancelled the Konflux build to save some CPU cycles, but I forgot it's a hard requirement now.

**Pull request merged**
