### PR TITLE
Revert "Merge pull request #2150 from zregvart/issue/EC-963"

### PR DESCRIPTION
**Pull request by robnester-rh**
Revert "Use given source URLs as keys in download cache"

This reverts commit 087f4659b10ada36b092d3f599e024d5c79ac955.

Ref: EC-1023
Signed-off-by: robnester-rh <rnester@redhat.com>

### CODE REVIEW

**Comment by simonbaird** [comment]
I think you need to revert the commit that makes the change not the merge commit.

**Comment by robnester-rh** [comment]
> I think you need to revert the commit that makes the change not the merge commit.

Ack. Done.

**Comment by robnester-rh** [comment]
> I think you need to revert the commit that makes the change not the merge commit.

Ack. Done.

**Comment by robnester-rh** [comment]
> Perhaps we should comment out the acceptance test [scenario](https://github.com/enterprise-contract/ec-cli/blob/eceee3c8e0481d017a8cf6ff7be5ed1ff7bd7ae7/features/validate_image.feature#L1124) that the original PR was trying to fix, otherwise we'll keep getting the [same failure](https://github.com/enterprise-contract/ec-cli/actions/runs/11921092450/job/33225846198#step:6:6312).

I've commented out that scenario in the latest commit.

**Review by lcarva — APPROVED** [review]

**Pull request merged**
