### PR TITLE
EC-908 Move GetPinnedURL func to go-gather.

### PR DESCRIPTION
**Pull request by robnester-rh**
This commit removes the GetPinnedURL function from ec-cli as it has been relocated to go-gather. This commit also makes the necessary changes to test files based on modifications of the GetPinnedURL function in go-gather.

### CODE REVIEW

**Review by zregvart — APPROVED** [review]

**Comment by simonbaird** [comment]
I think it's probably unblocked now since I changed the POLICY_CONFIGURATION param in the ITS.

**Comment by robnester-rh** [comment]
> I think it's probably unblocked now since I changed the POLICY_CONFIGURATION param in the ITS.

@simonbaird, seems to be still be blocked.

**Comment by simonbaird** [comment]
My fault, I mistyped the param.

**Comment by simonbaird** [comment]
:tada:

**Pull request merged**
